---
title: Langage R
---

Concepts R :


## Importation de données

## Restitution de données

### Affichage simple

### Sauvegarde dans une table à partir d'une autre

## Interrogation de données

cf slides 

- [Concepts pour l'interrogation de données](interrogation-concepts.html)
- [Interrogation de données sous R](interrogation-r.html)

## Manipulations supplémentaires

### Transposition de matice

### Autre ?

## Statistiques descriptives univariées

### Variable quantitative

#### Numérique

Moyenne, écart-type, minimum, maximum, ...

#### Graphique

Histogramme, boîte à moustache, QQ-plot

### Variable qualitative

#### Numérique

Occurences, fréquences

#### Graphique

Diagramme en barres, diagramme circulaire

## Statistiques descriptives bivariées

### Variables quantitative vs quantitative

#### Numérique

Covariance, coefficient de corrélation, ...

#### Graphique

Nuage de points

### Variables qualitative vs qualitative

#### Numérique

Table de contingence, table des fréquences, profils lignes, profils colonnes, chi2, ...

#### Graphique

Diagramme en barres séparées, diagramme barres empilées, diagrammes circulaires multiple, diagramme d'association

### Variables quantitative vs qualitative

#### Numérique

Moyenne, écart-type, minimum, maximum, ... par modalité

#### Graphique

Histogramme, boîte à moustache, QQ-plot par modalité

## Statistiques exploratoires

### Analyse en composants principales

### Analyse factorielle des correspondances

### Analyse factorielle des correspondances multiples

### Multidimensionnal Scaling

### Classification hiérarchique

### Classification directe
