---
title: "Manipulation de données avec R"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Présentation de R et de l'environnement

- [R](http://www.r-project.org)
- [RStudio](http://www.rstudio.com)
- [tidyverse](https://www.tidyverse.org/)

## Structure de données 

Tout est `vector` de base :

```{r}
1
class(1)
is.vector(1)
1:5
class(1:5)
is.vector(1:5)
```

Il existe aussi des `list` (nommées ou non, voire partiellement) :

```{r}
list(1:5, month.abb, pi)
class(list(1:5, month.abb, pi))
list(a = 1:5, mois = month.abb, pi = pi)
list(1:5, mois = month.abb, pi = pi)
```

le `data.frame` :

```{r}
mtcars
class(mtcars)
```

Dans `tidyverse`, utilisation du type [`tibble`](http://tibble.tidyverse.org/)

```{r}
library(tibble)
as_tibble(mtcars)
class(as_tibble(mtcars))
```


## Importation de données

[`readr`](http://readr.tidyverse.org/)

```{r}
library(readr)
```

```{r}
read_table("../donnees/")
```

[`readxl`](http://readxl.tidyverse.org/)

```{r}

```

[`haven`](http://haven.tidyverse.org/) : SAS, SPSS, ...

```{r}

```



## 